# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea79b8526836a6ee11c7a7c1ab81c2f3e32735c364783b79d850468181c0ac56a8ee81906891792bb8f9c6da4ffab49670599f5c0539608cbff96d824f999c59

test:
  secret_key_base: 90e7700b7df5a3a37fcb8240ccee725de11d21474035651b402e5396f67516f07b4c4d20ad281007de328aeab016dc22eb3d7ab766d80136b7f8eb113b55be6a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
